# Generated by Django 3.2.18 on 2023-08-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('experience', models.CharField(max_length=100, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
