# Generated by Django 3.2.21 on 2023-09-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('experience', models.CharField(max_length=100, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
