# Generated by Django 3.2.21 on 2023-09-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('confirm_password', models.CharField(max_length=100)),
            ],
        ),
    ]
