# Generated by Django 3.2.21 on 2023-09-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_registration_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Career',
        ),
    ]
