# Generated by Django 3.2.21 on 2023-09-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20230916_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
