# Generated by Django 3.2.21 on 2023-09-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_job_application_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_application',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
