# Generated by Django 3.2.21 on 2023-09-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_job_application_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_application',
            name='image',
        ),
        migrations.AddField(
            model_name='job_application',
            name='pdf_file',
            field=models.FileField(default='', upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
