# Generated by Django 3.2.22 on 2024-03-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_remove_career_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovtEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('venue', models.IntegerField(null=True)),
                ('pre_event_image', models.ImageField(upload_to='images')),
                ('mid_event_image', models.ImageField(upload_to='images')),
                ('post_event_image', models.ImageField(upload_to='images')),
                ('phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.assemblycategory')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.DeleteModel(
            name='Job_Application',
        ),
        migrations.AddField(
            model_name='govtevent',
            name='parliament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.parliamentcategory'),
        ),
    ]
